### ISSUE TITLE
New pages between sections

### ISSUE THREAD

**Issue by dechiara** [pgarner/erc#1]
Hello, I started using your template, so far I find it very useful. However I was wondering if it is possible to prevent starting a new page when a new section begins. I was trying to look into the .sty file but did not know what to change. Thanks a lot!

**Comment by pgarner** [comment]
It's probably the \include{section} lines.  If you don't want a new page 
then change them to \input{section}.

Phil

**Comment by dechiara** [comment]
yes, it works! Thank you!
